/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComingSoon: typeof import('./src/components/Global/ComingSoon.vue')['default']
    FadeTransition: typeof import('./src/components/Transition/FadeTransition.vue')['default']
    GlobalHeader: typeof import('./src/components/Global/GlobalHeader.vue')['default']
    IconMdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
